apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kafka-3
        service: kafka
    spec:
      imagePullSecrets:
        - name: bfdreg 
      containers:
        - name: server
          image: daocloud.io/zhengbo0/kafka
          ports:
            - containerPort: 9092
            - containerPort: 7203
          env:
            - name: BROKER_ID
              value: "3"
            - name: NUM_PARTITIONS
              value: "3"
            - name: ADVERTISED_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ZOOKEEPER_CONNECT
              value: "10.0.0.17:2181"	
          volumeMounts:
            - mountPath: /opt/kafka/data
              name: data
      volumes:
        - emptyDir: {}
          name: data
