apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    service: allKafka
spec:
  ports:
    - name: broker
      port: 9092
    - name: jmx
      port: 7203
  selector:
    service: kafka
